# Generated by Django 5.1.7 on 2025-03-10 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('budgetid', models.AutoField(db_column='budgetID', primary_key=True, serialize=False)),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('setbudget', models.DateTimeField(blank=True, null=True)),
                ('updatebudget', models.DateTimeField(blank=True, null=True)),
                ('checkbudget', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Budget',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('reportid', models.AutoField(db_column='reportID', primary_key=True, serialize=False)),
                ('startdate', models.DateTimeField(blank=True, db_column='startDate', null=True)),
                ('enddate', models.DateTimeField(blank=True, db_column='endDate', null=True)),
                ('generatereport', models.DateTimeField(blank=True, db_column='generateReport', null=True)),
            ],
            options={
                'db_table': 'Report',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transactionid', models.AutoField(db_column='transactionID', primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('addtransaction', models.DateTimeField(blank=True, null=True)),
                ('edittransaction', models.DateTimeField(blank=True, null=True)),
                ('deletetransaction', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Transaction',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('register', models.DateTimeField(blank=True, null=True)),
                ('login', models.DateTimeField(blank=True, null=True)),
                ('logout', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'User',
                'managed': False,
            },
        ),
    ]
