// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkUhlJ1txrkYW-sjqMqD-8KacmcTOImDY',
    appId: '1:93156499204:web:4ede3570e82c4546adfa51',
    messagingSenderId: '93156499204',
    projectId: 'fintrak-a2efa',
    authDomain: 'fintrak-a2efa.firebaseapp.com',
    storageBucket: 'fintrak-a2efa.firebasestorage.app',
    measurementId: 'G-EK6CX5NE3P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhx1URZEvN-SRpBPP5pVgscik8ZcTv4q4',
    appId: '1:93156499204:android:c25771ff545588d1adfa51',
    messagingSenderId: '93156499204',
    projectId: 'fintrak-a2efa',
    storageBucket: 'fintrak-a2efa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYLJuo1hGl6LqM07e-ZAywNTjgfVv0T1I',
    appId: '1:93156499204:ios:a1d32b5fae9ba17fadfa51',
    messagingSenderId: '93156499204',
    projectId: 'fintrak-a2efa',
    storageBucket: 'fintrak-a2efa.firebasestorage.app',
    iosBundleId: 'com.example.fintrak',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYLJuo1hGl6LqM07e-ZAywNTjgfVv0T1I',
    appId: '1:93156499204:ios:a1d32b5fae9ba17fadfa51',
    messagingSenderId: '93156499204',
    projectId: 'fintrak-a2efa',
    storageBucket: 'fintrak-a2efa.firebasestorage.app',
    iosBundleId: 'com.example.fintrak',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDkUhlJ1txrkYW-sjqMqD-8KacmcTOImDY',
    appId: '1:93156499204:web:e47472528f17b1faadfa51',
    messagingSenderId: '93156499204',
    projectId: 'fintrak-a2efa',
    authDomain: 'fintrak-a2efa.firebaseapp.com',
    storageBucket: 'fintrak-a2efa.firebasestorage.app',
    measurementId: 'G-FCJZ1VTJ6K',
  );
}
